### ISSUE TITLE
Create rake task to cleanup old todos

### ISSUE THREAD

**Issue by hopsoft** [hopsoft/stimulus_reflex_todomvc#12]
The demo is hosted on free Heroku services. We need a rake task that will delete todos that are older than 2 weeks or something along those lines to ensure we don't exhaust the Heroku pg row limits on the free plan.

**Comment by lucianolima00** [comment]
Hey @hopsoft, I will do this issue. This will be my first open-source contribution

**Comment by hopsoft** [comment]
Awesome. Let me know if you need any help.

**Comment by hopsoft** [comment]
Also, we can port your PR to this project when ready. https://github.com/hopsoft/stimulus_todomvc/issues/6

You'll get 2 contributions from the same effort :)

**Comment by lucianolima00** [comment]
I created a PR to the second project. https://github.com/hopsoft/stimulus_todomvc/pull/7

**Comment by andrewmcodes** [comment]
@hopsoft what do you think about adding [Heroku scheduler](https://elements.heroku.com/addons/scheduler) that runs the rake task once per day? Seems like an easy way to automate.

**Comment by hopsoft** [comment]
Exactly what I was planning on.

**Comment by hopsoft** [comment]
Resolved by #12
