### ISSUE TITLE
app/controller structure

### ISSUE THREAD

**Issue by pjforde1978** [hopsoft/stimulus_reflex_todomvc#17]
I noticed that you actually create a Todos controller on every todo element. This has to create a lot more overhead than necessary. It's the sort of thing that doesn't matter in a sample but in a shipping app, you probably want to optimize.

Why not set the controller on the parent section element in index.html.erb? So far as I can tell, the actual contents of the controller wouldn't change, because we're still operating on the event passed to the cancelEdit method.

Meanwhile, I noticed that the keypress event does not fire when you hit escape, meaning that the whole exercise with having a Todos controller and cancelEdit method was actually moot! ha.

However, I actually think escape key support is a good thing so I looked into the state of the art for key events; switching to keydown from keypress is probably the way to go. Here is my revised cancelEdit... I can submit a PR if you want!

```
  cancelEdit (event) {
    if (event.type === 'keydown' && !['Escape', 'Esc'].includes(event.key)) {
      return
    }
    this.stimulate('TodosReflex#cancel_edit')
  }
```

**Comment by MatiasFMolinari** [comment]
merged on #18
